### ISSUE TITLE
Document deployment steps

### ISSUE THREAD

**Issue by paulsharpeY** [benwhalley/lifesavR#12]
Currently deploying from `docs/`, but not sure if you want to deploy directly from `website/` post reorganisation. It's worth documenting this so authors know what to push to deploy.

**Comment by benwhalley** [comment]
The _build.R script builds them into /docs, so it currently works if you use that. It’s nice because you get less just in /website

Ben



On 2 Sep 2021, at 13:55, paulsharpeY ***@***.******@***.***>> wrote:



Currently deploying from docs/, but not sure if you want to deploy directly from website/ post reorganisation. It's worth documenting this so authors know what to push to deploy.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbenwhalley%2FlifesavR%2Fissues%2F12&data=04%7C01%7Cben.whalley%40plymouth.ac.uk%7C2b651ca4aa9d4c39aa2308d96e10e18c%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637661841042499078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ok4DZdUrkzHHMhb%2BJSp%2FxExZ26HFs5VhjtMGTs1YDbc%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAEADGGXQYMRDILFBS4AJY3T75X2NANCNFSM5DJBKW3A&data=04%7C01%7Cben.whalley%40plymouth.ac.uk%7C2b651ca4aa9d4c39aa2308d96e10e18c%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637661841042499078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SgIaXgM%2FyAZuIblV8OXMdOejD2pgnXE9aZvW9%2BiBP0Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cben.whalley%40plymouth.ac.uk%7C2b651ca4aa9d4c39aa2308d96e10e18c%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637661841042509068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4T%2BqIUj8RFsV4vZQJaXEB6rHg78U%2Fo8ot8nHdAU3tg0%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cben.whalley%40plymouth.ac.uk%7C2b651ca4aa9d4c39aa2308d96e10e18c%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637661841042509068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PzqnpeuWKCSd8XsiLTrJVPCdzHGG183SDVaQ4pSCzds%3D&reserved=0>.

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by paulsharpeY** [comment]
Resolved by bef6091.
